# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 563)
        MainWindow.setMinimumSize(QtCore.QSize(800, 550))
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background:#0f2027;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toodle = QtWidgets.QFrame(self.frame_top)
        self.frame_toodle.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_toodle.setMaximumSize(QtCore.QSize(80, 55))
        self.frame_toodle.setStyleSheet("background:rgb(0,143,150);")
        self.frame_toodle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toodle.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_toodle.setObjectName("frame_toodle")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_toodle)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toodle = QtWidgets.QPushButton(self.frame_toodle)
        self.toodle.setMinimumSize(QtCore.QSize(80, 55))
        self.toodle.setMaximumSize(QtCore.QSize(80, 55))
        self.toodle.setStyleSheet("QPushButton {\n"
"    image: url(:/icons/icons/1x/logo.png);\n"
"    border: none;\n"
"    background-color: #0f2027;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,178,178);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.toodle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Users/kiongoss/.designer/FinalYearProject/src/icons/1x/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toodle.setIcon(icon)
        self.toodle.setIconSize(QtCore.QSize(22, 12))
        self.toodle.setFlat(True)
        self.toodle.setObjectName("toodle")
        self.horizontalLayout_3.addWidget(self.toodle)
        self.horizontalLayout.addWidget(self.frame_toodle)
        self.frame_top_east = QtWidgets.QFrame(self.frame_top)
        self.frame_top_east.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_top_east.setStyleSheet("background:#0f2027;")
        self.frame_top_east.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_east.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top_east.setObjectName("frame_top_east")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_east)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_appname = QtWidgets.QFrame(self.frame_top_east)
        self.frame_appname.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_appname.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_appname.setObjectName("frame_appname")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_appname)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(7)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lab_appname = QtWidgets.QLabel(self.frame_appname)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(24)
        self.lab_appname.setFont(font)
        self.lab_appname.setStyleSheet("color:rgb(255,255,255);")
        self.lab_appname.setObjectName("lab_appname")
        self.horizontalLayout_10.addWidget(self.lab_appname)
        self.horizontalLayout_4.addWidget(self.frame_appname)
        self.frame_user = QtWidgets.QFrame(self.frame_top_east)
        self.frame_user.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_user.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_user.setObjectName("frame_user")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_user)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_4.addWidget(self.frame_user)
        self.frame_person = QtWidgets.QFrame(self.frame_top_east)
        self.frame_person.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_person.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_person.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_person.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_person.setObjectName("frame_person")
        self.pushButton = QtWidgets.QPushButton(self.frame_person)
        self.pushButton.setGeometry(QtCore.QRect(0, 16, 55, 31))
        self.pushButton.setStyleSheet("image: url(:/icons/icons/1x/peple.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.frame_person)
        self.frame_min = QtWidgets.QFrame(self.frame_top_east)
        self.frame_min.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_min.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_min.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_min.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_min.setObjectName("frame_min")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_min)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.bn_min = QtWidgets.QPushButton(self.frame_min)
        self.bn_min.setMaximumSize(QtCore.QSize(55, 55))
        self.bn_min.setStyleSheet("QPushButton {\n"
"    image: url(:/icons/icons/1x/hideAsset 53.png);\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_min.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Users/kiongoss/.designer/FinalYearProject/src/icons/1x/hideAsset 53.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_min.setIcon(icon1)
        self.bn_min.setIconSize(QtCore.QSize(22, 22))
        self.bn_min.setFlat(True)
        self.bn_min.setObjectName("bn_min")
        self.horizontalLayout_7.addWidget(self.bn_min)
        self.horizontalLayout_4.addWidget(self.frame_min)
        self.frame_max = QtWidgets.QFrame(self.frame_top_east)
        self.frame_max.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_max.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_max.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_max.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_max.setObjectName("frame_max")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_max)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bn_max = QtWidgets.QPushButton(self.frame_max)
        self.bn_max.setMaximumSize(QtCore.QSize(55, 55))
        self.bn_max.setStyleSheet("QPushButton {\n"
"    image: url(:/icons/icons/1x/max.png);\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_max.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Users/kiongoss/.designer/FinalYearProject/src/icons/1x/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_max.setIcon(icon2)
        self.bn_max.setIconSize(QtCore.QSize(22, 22))
        self.bn_max.setFlat(True)
        self.bn_max.setObjectName("bn_max")
        self.horizontalLayout_6.addWidget(self.bn_max)
        self.horizontalLayout_4.addWidget(self.frame_max)
        self.frame_close = QtWidgets.QFrame(self.frame_top_east)
        self.frame_close.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_close.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_close.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_close.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_close.setObjectName("frame_close")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_close)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bn_close = QtWidgets.QPushButton(self.frame_close)
        self.bn_close.setMaximumSize(QtCore.QSize(55, 55))
        self.bn_close.setStyleSheet("QPushButton {\n"
"    image: url(:/icons/icons/1x/closeAsset 43.png);\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: red;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../Users/kiongoss/.designer/FinalYearProject/src/icons/1x/closeAsset 43.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_close.setIcon(icon3)
        self.bn_close.setIconSize(QtCore.QSize(22, 22))
        self.bn_close.setFlat(True)
        self.bn_close.setObjectName("bn_close")
        self.horizontalLayout_5.addWidget(self.bn_close)
        self.horizontalLayout_4.addWidget(self.frame_close)
        self.horizontalLayout.addWidget(self.frame_top_east)
        self.gridLayout_3.addWidget(self.frame_top, 0, 0, 1, 1)
        self.frame_bottom = QtWidgets.QFrame(self.centralwidget)
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bottom.setObjectName("frame_bottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_bottom)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_bottom_west = QtWidgets.QFrame(self.frame_bottom)
        self.frame_bottom_west.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_bottom_west.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_bottom_west.setStyleSheet("background:#0f2027;")
        self.frame_bottom_west.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom_west.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bottom_west.setObjectName("frame_bottom_west")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_bottom_west)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_home = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_home.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_home.setMaximumSize(QtCore.QSize(160, 55))
        self.frame_home.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_home.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_home.setObjectName("frame_home")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_home)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.bn_home = QtWidgets.QPushButton(self.frame_home)
        self.bn_home.setMinimumSize(QtCore.QSize(80, 55))
        self.bn_home.setMaximumSize(QtCore.QSize(160, 55))
        self.bn_home.setStyleSheet("QPushButton {\n"
"    image: url(:/icons/icons/1x/homeAsset 46.png);\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#2c5364;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_home.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../Users/kiongoss/.designer/FinalYearProject/src/icons/1x/homeAsset 46.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_home.setIcon(icon4)
        self.bn_home.setIconSize(QtCore.QSize(22, 22))
        self.bn_home.setFlat(True)
        self.bn_home.setObjectName("bn_home")
        self.horizontalLayout_15.addWidget(self.bn_home)
        self.verticalLayout_3.addWidget(self.frame_home)
        self.frame_bug = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_bug.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_bug.setMaximumSize(QtCore.QSize(160, 55))
        self.frame_bug.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bug.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bug.setObjectName("frame_bug")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_bug)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.bn_bug = QtWidgets.QPushButton(self.frame_bug)
        self.bn_bug.setMinimumSize(QtCore.QSize(80, 55))
        self.bn_bug.setMaximumSize(QtCore.QSize(160, 55))
        self.bn_bug.setStyleSheet("QPushButton {\n"
"    image: url(:/icons/icons/1x/bugAsset 47.png);\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#2c5364;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_bug.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../Users/kiongoss/.designer/FinalYearProject/src/icons/1x/bugAsset 47.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_bug.setIcon(icon5)
        self.bn_bug.setIconSize(QtCore.QSize(22, 22))
        self.bn_bug.setFlat(True)
        self.bn_bug.setObjectName("bn_bug")
        self.horizontalLayout_16.addWidget(self.bn_bug)
        self.verticalLayout_3.addWidget(self.frame_bug)
        self.frame_cloud = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_cloud.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_cloud.setMaximumSize(QtCore.QSize(160, 55))
        self.frame_cloud.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_cloud.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_cloud.setObjectName("frame_cloud")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_cloud)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.bn_cloud = QtWidgets.QPushButton(self.frame_cloud)
        self.bn_cloud.setMinimumSize(QtCore.QSize(80, 55))
        self.bn_cloud.setMaximumSize(QtCore.QSize(160, 55))
        self.bn_cloud.setStyleSheet("QPushButton {\n"
"    image: url(:/icons/icons/1x/cloudAsset 48.png);\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#2c5364;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_cloud.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../Users/kiongoss/.designer/FinalYearProject/src/icons/1x/cloudAsset 48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_cloud.setIcon(icon6)
        self.bn_cloud.setIconSize(QtCore.QSize(22, 12))
        self.bn_cloud.setFlat(True)
        self.bn_cloud.setObjectName("bn_cloud")
        self.horizontalLayout_17.addWidget(self.bn_cloud)
        self.verticalLayout_3.addWidget(self.frame_cloud)
        self.frame_android = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_android.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_android.setMaximumSize(QtCore.QSize(160, 55))
        self.frame_android.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android.setObjectName("frame_android")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_android)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.bn_android = QtWidgets.QPushButton(self.frame_android)
        self.bn_android.setMinimumSize(QtCore.QSize(80, 55))
        self.bn_android.setMaximumSize(QtCore.QSize(160, 55))
        self.bn_android.setStyleSheet("QPushButton {\n"
"    image: url(:/icons/icons/1x/androidAsset 49.png);\n"
"    \n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#2c5364;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_android.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../Users/kiongoss/.designer/FinalYearProject/src/icons/1x/androidAsset 49.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_android.setIcon(icon7)
        self.bn_android.setIconSize(QtCore.QSize(20, 22))
        self.bn_android.setFlat(True)
        self.bn_android.setObjectName("bn_android")
        self.horizontalLayout_18.addWidget(self.bn_android)
        self.verticalLayout_3.addWidget(self.frame_android)
        self.frame_8 = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3.addWidget(self.frame_8)
        self.horizontalLayout_2.addWidget(self.frame_bottom_west)
        self.frame_bottom_east = QtWidgets.QFrame(self.frame_bottom)
        self.frame_bottom_east.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom_east.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bottom_east.setObjectName("frame_bottom_east")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_bottom_east)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_bottom_east)
        self.frame.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 55))
        self.stackedWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 246, 255), stop:0.55 rgba(255, 255, 225, 255), stop:1 rgba(34, 72, 88, 255));")
        self.stackedWidget.setObjectName("stackedWidget")
        self.add_remove_wishlist = QtWidgets.QWidget()
        self.add_remove_wishlist.setObjectName("add_remove_wishlist")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.add_remove_wishlist)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.add_remove_frame = QtWidgets.QFrame(self.add_remove_wishlist)
        self.add_remove_frame.setMinimumSize(QtCore.QSize(702, 457))
        self.add_remove_frame.setMaximumSize(QtCore.QSize(702, 457))
        self.add_remove_frame.setStyleSheet("QFrame{\n"
"background-color:#FFFFF0;\n"
"border-radius:10px;\n"
"box-shadow: 0 3px 10px rgb(0 0 0 / 0.2);\n"
"}\n"
"QLineEdit {\n"
" color:black;\n"
" border:1px solid #0f2027;\n"
" border-radius:4px;\n"
" background:#f2f2f2;\n"
"}\n"
"QLineEdit:hover {\n"
" \n"
" border:2px solid  #33cc33;\n"
" border-radius:4px;\n"
" background: #ffffff;\n"
"}\n"
"QLineEdit:disabled {\n"
" \n"
" border:2px solid#0f2027;\n"
" border-radius:4px;\n"
" background:#0f2027;\n"
"}\n"
"")
        self.add_remove_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.add_remove_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_remove_frame.setObjectName("add_remove_frame")
        self.add_remove_label = QtWidgets.QLabel(self.add_remove_frame)
        self.add_remove_label.setGeometry(QtCore.QRect(10, 10, 691, 29))
        self.add_remove_label.setObjectName("add_remove_label")
        self.car_deatils_label = QtWidgets.QLabel(self.add_remove_frame)
        self.car_deatils_label.setGeometry(QtCore.QRect(20, 45, 111, 19))
        self.car_deatils_label.setObjectName("car_deatils_label")
        self.reg_plate_label = QtWidgets.QLabel(self.add_remove_frame)
        self.reg_plate_label.setGeometry(QtCore.QRect(10, 70, 134, 19))
        self.reg_plate_label.setObjectName("reg_plate_label")
        self.owner_label = QtWidgets.QLabel(self.add_remove_frame)
        self.owner_label.setGeometry(QtCore.QRect(10, 101, 58, 19))
        self.owner_label.setObjectName("owner_label")
        self.vehicle_make_label = QtWidgets.QLabel(self.add_remove_frame)
        self.vehicle_make_label.setGeometry(QtCore.QRect(10, 132, 102, 19))
        self.vehicle_make_label.setObjectName("vehicle_make_label")
        self.year_of_man_label = QtWidgets.QLabel(self.add_remove_frame)
        self.year_of_man_label.setGeometry(QtCore.QRect(10, 163, 153, 19))
        self.year_of_man_label.setObjectName("year_of_man_label")
        self.engine_capacity_label = QtWidgets.QLabel(self.add_remove_frame)
        self.engine_capacity_label.setGeometry(QtCore.QRect(10, 194, 123, 19))
        self.engine_capacity_label.setObjectName("engine_capacity_label")
        self.body_type_label = QtWidgets.QLabel(self.add_remove_frame)
        self.body_type_label.setGeometry(QtCore.QRect(10, 225, 141, 19))
        self.body_type_label.setObjectName("body_type_label")
        self.color_label = QtWidgets.QLabel(self.add_remove_frame)
        self.color_label.setGeometry(QtCore.QRect(10, 256, 49, 19))
        self.color_label.setObjectName("color_label")
        self.logbook_number_label = QtWidgets.QLabel(self.add_remove_frame)
        self.logbook_number_label.setGeometry(QtCore.QRect(10, 287, 213, 19))
        self.logbook_number_label.setObjectName("logbook_number_label")
        self.engine_number_label = QtWidgets.QLabel(self.add_remove_frame)
        self.engine_number_label.setGeometry(QtCore.QRect(10, 318, 210, 19))
        self.engine_number_label.setObjectName("engine_number_label")
        self.chassis_number_label = QtWidgets.QLabel(self.add_remove_frame)
        self.chassis_number_label.setGeometry(QtCore.QRect(10, 349, 221, 19))
        self.chassis_number_label.setObjectName("chassis_number_label")
        self.frame_5 = QtWidgets.QFrame(self.add_remove_frame)
        self.frame_5.setGeometry(QtCore.QRect(150, 380, 431, 71))
        self.frame_5.setMinimumSize(QtCore.QSize(431, 71))
        self.frame_5.setMaximumSize(QtCore.QSize(431, 71))
        self.frame_5.setStyleSheet("\n"
"    background-color: #FFFFF0;\n"
"\n"
"\n"
"QRadioButton {\n"
"    background#0f2027;\n"
"    color:white;\n"
"} \n"
"QRadioButton::indicator {\n"
"    width:10px;\n"
"    height:10px;\n"
"    border-radius: 7px; }\n"
"QRadioButton::indicator:checked {\n"
"    background-color:#0f2027;\n"
"    border: 2px solid rgb(51,51,51);\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:rgb(91,90,90);\n"
"    border:2px solid rgb(51,51,51);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.btn_save_to_wishlist = QtWidgets.QPushButton(self.frame_5)
        self.btn_save_to_wishlist.setGeometry(QtCore.QRect(120, 30, 131, 31))
        self.btn_save_to_wishlist.setMinimumSize(QtCore.QSize(69, 25))
        self.btn_save_to_wishlist.setMaximumSize(QtCore.QSize(69000, 25000))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_save_to_wishlist.setFont(font)
        self.btn_save_to_wishlist.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save_to_wishlist.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color:#0f2027;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.btn_save_to_wishlist.setObjectName("btn_save_to_wishlist")
        self.reg_plate_input = QtWidgets.QLineEdit(self.add_remove_frame)
        self.reg_plate_input.setEnabled(True)
        self.reg_plate_input.setGeometry(QtCore.QRect(229, 70, 463, 25))
        self.reg_plate_input.setMinimumSize(QtCore.QSize(400, 25))
        self.reg_plate_input.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.reg_plate_input.setFont(font)
        self.reg_plate_input.setStyleSheet("")
        self.reg_plate_input.setClearButtonEnabled(True)
        self.reg_plate_input.setObjectName("reg_plate_input")
        self.logbook_number_input = QtWidgets.QLineEdit(self.add_remove_frame)
        self.logbook_number_input.setEnabled(True)
        self.logbook_number_input.setGeometry(QtCore.QRect(229, 287, 463, 25))
        self.logbook_number_input.setMinimumSize(QtCore.QSize(400, 25))
        self.logbook_number_input.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.logbook_number_input.setFont(font)
        self.logbook_number_input.setStyleSheet("")
        self.logbook_number_input.setClearButtonEnabled(True)
        self.logbook_number_input.setObjectName("logbook_number_input")
        self.engine_number_input = QtWidgets.QLineEdit(self.add_remove_frame)
        self.engine_number_input.setEnabled(True)
        self.engine_number_input.setGeometry(QtCore.QRect(229, 318, 463, 25))
        self.engine_number_input.setMinimumSize(QtCore.QSize(400, 25))
        self.engine_number_input.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.engine_number_input.setFont(font)
        self.engine_number_input.setStyleSheet("")
        self.engine_number_input.setClearButtonEnabled(True)
        self.engine_number_input.setObjectName("engine_number_input")
        self.chassis_number_label_2 = QtWidgets.QLineEdit(self.add_remove_frame)
        self.chassis_number_label_2.setEnabled(True)
        self.chassis_number_label_2.setGeometry(QtCore.QRect(229, 349, 463, 25))
        self.chassis_number_label_2.setMinimumSize(QtCore.QSize(400, 25))
        self.chassis_number_label_2.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.chassis_number_label_2.setFont(font)
        self.chassis_number_label_2.setStyleSheet("")
        self.chassis_number_label_2.setClearButtonEnabled(True)
        self.chassis_number_label_2.setObjectName("chassis_number_label_2")
        self.color_input = QtWidgets.QLineEdit(self.add_remove_frame)
        self.color_input.setEnabled(True)
        self.color_input.setGeometry(QtCore.QRect(229, 256, 463, 25))
        self.color_input.setMinimumSize(QtCore.QSize(400, 25))
        self.color_input.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.color_input.setFont(font)
        self.color_input.setStyleSheet("")
        self.color_input.setClearButtonEnabled(True)
        self.color_input.setObjectName("color_input")
        self.body_type_input = QtWidgets.QLineEdit(self.add_remove_frame)
        self.body_type_input.setEnabled(True)
        self.body_type_input.setGeometry(QtCore.QRect(229, 225, 463, 25))
        self.body_type_input.setMinimumSize(QtCore.QSize(400, 25))
        self.body_type_input.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.body_type_input.setFont(font)
        self.body_type_input.setStyleSheet("")
        self.body_type_input.setClearButtonEnabled(True)
        self.body_type_input.setObjectName("body_type_input")
        self.engine_capacity_input = QtWidgets.QLineEdit(self.add_remove_frame)
        self.engine_capacity_input.setEnabled(True)
        self.engine_capacity_input.setGeometry(QtCore.QRect(229, 194, 463, 25))
        self.engine_capacity_input.setMinimumSize(QtCore.QSize(400, 25))
        self.engine_capacity_input.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.engine_capacity_input.setFont(font)
        self.engine_capacity_input.setStyleSheet("")
        self.engine_capacity_input.setClearButtonEnabled(True)
        self.engine_capacity_input.setObjectName("engine_capacity_input")
        self.year_of_man_input = QtWidgets.QLineEdit(self.add_remove_frame)
        self.year_of_man_input.setEnabled(True)
        self.year_of_man_input.setGeometry(QtCore.QRect(229, 163, 463, 25))
        self.year_of_man_input.setMinimumSize(QtCore.QSize(400, 25))
        self.year_of_man_input.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.year_of_man_input.setFont(font)
        self.year_of_man_input.setStyleSheet("")
        self.year_of_man_input.setClearButtonEnabled(True)
        self.year_of_man_input.setObjectName("year_of_man_input")
        self.vehicle_make_input = QtWidgets.QLineEdit(self.add_remove_frame)
        self.vehicle_make_input.setEnabled(True)
        self.vehicle_make_input.setGeometry(QtCore.QRect(229, 132, 463, 25))
        self.vehicle_make_input.setMinimumSize(QtCore.QSize(400, 25))
        self.vehicle_make_input.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.vehicle_make_input.setFont(font)
        self.vehicle_make_input.setStyleSheet("")
        self.vehicle_make_input.setClearButtonEnabled(True)
        self.vehicle_make_input.setObjectName("vehicle_make_input")
        self.owner_input = QtWidgets.QLineEdit(self.add_remove_frame)
        self.owner_input.setEnabled(True)
        self.owner_input.setGeometry(QtCore.QRect(229, 101, 463, 25))
        self.owner_input.setMinimumSize(QtCore.QSize(400, 25))
        self.owner_input.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.owner_input.setFont(font)
        self.owner_input.setStyleSheet("")
        self.owner_input.setClearButtonEnabled(True)
        self.owner_input.setObjectName("owner_input")
        self.gridLayout_7.addWidget(self.add_remove_frame, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.add_remove_wishlist)
        self.search_registration = QtWidgets.QWidget()
        self.search_registration.setObjectName("search_registration")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.search_registration)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.add_remove_frame_2 = QtWidgets.QFrame(self.search_registration)
        self.add_remove_frame_2.setMinimumSize(QtCore.QSize(702, 457))
        self.add_remove_frame_2.setMaximumSize(QtCore.QSize(702, 457))
        self.add_remove_frame_2.setStyleSheet("QFrame{\n"
"background-color:#FFFFF0;\n"
"border-radius:10px;\n"
"box-shadow: 0 3px 10px rgb(0 0 0 / 0.2);\n"
"}\n"
"QLineEdit {\n"
" color:black;\n"
" border:1px solid #0f2027;\n"
" border-radius:4px;\n"
" background:#f2f2f2;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
" \n"
" border:2px solid#0f2027;\n"
" border-radius:4px;\n"
" background:#0f2027;\n"
"}\n"
"")
        self.add_remove_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.add_remove_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_remove_frame_2.setObjectName("add_remove_frame_2")
        self.add_remove_label_2 = QtWidgets.QLabel(self.add_remove_frame_2)
        self.add_remove_label_2.setGeometry(QtCore.QRect(10, 10, 691, 29))
        self.add_remove_label_2.setObjectName("add_remove_label_2")
        self.car_deatils_label_2 = QtWidgets.QLabel(self.add_remove_frame_2)
        self.car_deatils_label_2.setGeometry(QtCore.QRect(10, 130, 111, 19))
        self.car_deatils_label_2.setObjectName("car_deatils_label_2")
        self.reg_plate_label_2 = QtWidgets.QLabel(self.add_remove_frame_2)
        self.reg_plate_label_2.setGeometry(QtCore.QRect(10, 155, 134, 19))
        self.reg_plate_label_2.setObjectName("reg_plate_label_2")
        self.owner_label_2 = QtWidgets.QLabel(self.add_remove_frame_2)
        self.owner_label_2.setGeometry(QtCore.QRect(10, 186, 58, 19))
        self.owner_label_2.setObjectName("owner_label_2")
        self.vehicle_make_label_2 = QtWidgets.QLabel(self.add_remove_frame_2)
        self.vehicle_make_label_2.setGeometry(QtCore.QRect(10, 217, 102, 19))
        self.vehicle_make_label_2.setObjectName("vehicle_make_label_2")
        self.year_of_man_label_2 = QtWidgets.QLabel(self.add_remove_frame_2)
        self.year_of_man_label_2.setGeometry(QtCore.QRect(10, 245, 153, 19))
        self.year_of_man_label_2.setObjectName("year_of_man_label_2")
        self.engine_capacity_label_2 = QtWidgets.QLabel(self.add_remove_frame_2)
        self.engine_capacity_label_2.setGeometry(QtCore.QRect(10, 275, 123, 19))
        self.engine_capacity_label_2.setObjectName("engine_capacity_label_2")
        self.body_type_label_2 = QtWidgets.QLabel(self.add_remove_frame_2)
        self.body_type_label_2.setGeometry(QtCore.QRect(10, 306, 141, 19))
        self.body_type_label_2.setObjectName("body_type_label_2")
        self.color_label_2 = QtWidgets.QLabel(self.add_remove_frame_2)
        self.color_label_2.setGeometry(QtCore.QRect(10, 335, 49, 19))
        self.color_label_2.setObjectName("color_label_2")
        self.logbook_number_label_2 = QtWidgets.QLabel(self.add_remove_frame_2)
        self.logbook_number_label_2.setGeometry(QtCore.QRect(10, 365, 213, 19))
        self.logbook_number_label_2.setObjectName("logbook_number_label_2")
        self.engine_number_label_2 = QtWidgets.QLabel(self.add_remove_frame_2)
        self.engine_number_label_2.setGeometry(QtCore.QRect(10, 395, 210, 19))
        self.engine_number_label_2.setObjectName("engine_number_label_2")
        self.chassis_number_label_3 = QtWidgets.QLabel(self.add_remove_frame_2)
        self.chassis_number_label_3.setGeometry(QtCore.QRect(10, 425, 221, 19))
        self.chassis_number_label_3.setObjectName("chassis_number_label_3")
        self.reg_plate_input_2 = QtWidgets.QLineEdit(self.add_remove_frame_2)
        self.reg_plate_input_2.setEnabled(True)
        self.reg_plate_input_2.setGeometry(QtCore.QRect(229, 155, 463, 25))
        self.reg_plate_input_2.setMinimumSize(QtCore.QSize(400, 25))
        self.reg_plate_input_2.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.reg_plate_input_2.setFont(font)
        self.reg_plate_input_2.setStyleSheet("")
        self.reg_plate_input_2.setReadOnly(True)
        self.reg_plate_input_2.setObjectName("reg_plate_input_2")
        self.logbook_number_input_2 = QtWidgets.QLineEdit(self.add_remove_frame_2)
        self.logbook_number_input_2.setEnabled(True)
        self.logbook_number_input_2.setGeometry(QtCore.QRect(229, 365, 463, 25))
        self.logbook_number_input_2.setMinimumSize(QtCore.QSize(400, 25))
        self.logbook_number_input_2.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.logbook_number_input_2.setFont(font)
        self.logbook_number_input_2.setStyleSheet("")
        self.logbook_number_input_2.setReadOnly(True)
        self.logbook_number_input_2.setObjectName("logbook_number_input_2")
        self.engine_number_input_2 = QtWidgets.QLineEdit(self.add_remove_frame_2)
        self.engine_number_input_2.setEnabled(True)
        self.engine_number_input_2.setGeometry(QtCore.QRect(229, 395, 463, 25))
        self.engine_number_input_2.setMinimumSize(QtCore.QSize(400, 25))
        self.engine_number_input_2.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.engine_number_input_2.setFont(font)
        self.engine_number_input_2.setStyleSheet("")
        self.engine_number_input_2.setReadOnly(True)
        self.engine_number_input_2.setObjectName("engine_number_input_2")
        self.chassis_number_label_4 = QtWidgets.QLineEdit(self.add_remove_frame_2)
        self.chassis_number_label_4.setEnabled(True)
        self.chassis_number_label_4.setGeometry(QtCore.QRect(229, 425, 463, 25))
        self.chassis_number_label_4.setMinimumSize(QtCore.QSize(400, 25))
        self.chassis_number_label_4.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.chassis_number_label_4.setFont(font)
        self.chassis_number_label_4.setStyleSheet("")
        self.chassis_number_label_4.setReadOnly(True)
        self.chassis_number_label_4.setObjectName("chassis_number_label_4")
        self.color_input_2 = QtWidgets.QLineEdit(self.add_remove_frame_2)
        self.color_input_2.setEnabled(True)
        self.color_input_2.setGeometry(QtCore.QRect(229, 335, 463, 25))
        self.color_input_2.setMinimumSize(QtCore.QSize(400, 25))
        self.color_input_2.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.color_input_2.setFont(font)
        self.color_input_2.setStyleSheet("")
        self.color_input_2.setReadOnly(True)
        self.color_input_2.setObjectName("color_input_2")
        self.body_type_input_2 = QtWidgets.QLineEdit(self.add_remove_frame_2)
        self.body_type_input_2.setEnabled(True)
        self.body_type_input_2.setGeometry(QtCore.QRect(229, 305, 463, 25))
        self.body_type_input_2.setMinimumSize(QtCore.QSize(400, 25))
        self.body_type_input_2.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.body_type_input_2.setFont(font)
        self.body_type_input_2.setStyleSheet("")
        self.body_type_input_2.setReadOnly(True)
        self.body_type_input_2.setObjectName("body_type_input_2")
        self.engine_capacity_input_2 = QtWidgets.QLineEdit(self.add_remove_frame_2)
        self.engine_capacity_input_2.setEnabled(True)
        self.engine_capacity_input_2.setGeometry(QtCore.QRect(229, 275, 463, 25))
        self.engine_capacity_input_2.setMinimumSize(QtCore.QSize(400, 25))
        self.engine_capacity_input_2.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.engine_capacity_input_2.setFont(font)
        self.engine_capacity_input_2.setStyleSheet("")
        self.engine_capacity_input_2.setReadOnly(True)
        self.engine_capacity_input_2.setObjectName("engine_capacity_input_2")
        self.year_of_man_input_2 = QtWidgets.QLineEdit(self.add_remove_frame_2)
        self.year_of_man_input_2.setEnabled(True)
        self.year_of_man_input_2.setGeometry(QtCore.QRect(229, 245, 463, 25))
        self.year_of_man_input_2.setMinimumSize(QtCore.QSize(400, 25))
        self.year_of_man_input_2.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.year_of_man_input_2.setFont(font)
        self.year_of_man_input_2.setStyleSheet("")
        self.year_of_man_input_2.setReadOnly(True)
        self.year_of_man_input_2.setObjectName("year_of_man_input_2")
        self.vehicle_make_input_2 = QtWidgets.QLineEdit(self.add_remove_frame_2)
        self.vehicle_make_input_2.setEnabled(True)
        self.vehicle_make_input_2.setGeometry(QtCore.QRect(229, 215, 463, 25))
        self.vehicle_make_input_2.setMinimumSize(QtCore.QSize(400, 25))
        self.vehicle_make_input_2.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.vehicle_make_input_2.setFont(font)
        self.vehicle_make_input_2.setStyleSheet("")
        self.vehicle_make_input_2.setReadOnly(True)
        self.vehicle_make_input_2.setObjectName("vehicle_make_input_2")
        self.owner_input_2 = QtWidgets.QLineEdit(self.add_remove_frame_2)
        self.owner_input_2.setEnabled(True)
        self.owner_input_2.setGeometry(QtCore.QRect(229, 185, 463, 25))
        self.owner_input_2.setMinimumSize(QtCore.QSize(400, 25))
        self.owner_input_2.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.owner_input_2.setFont(font)
        self.owner_input_2.setStyleSheet("")
        self.owner_input_2.setReadOnly(True)
        self.owner_input_2.setObjectName("owner_input_2")
        self.search_box = QtWidgets.QLineEdit(self.add_remove_frame_2)
        self.search_box.setEnabled(True)
        self.search_box.setGeometry(QtCore.QRect(10, 40, 551, 41))
        self.search_box.setMinimumSize(QtCore.QSize(400, 25))
        self.search_box.setMaximumSize(QtCore.QSize(500000, 250000))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.search_box.setFont(font)
        self.search_box.setStyleSheet("QLineEdit {\n"
" color:black;\n"
" border:1px solid #0f2027;\n"
" border-radius:4px;\n"
" background:#ffffff;\n"
"}\n"
"QLineEdit:hover {\n"
"\n"
" border:2px solid  #33cc33;\n"
" border-radius:4px;\n"
" background: #ffffff;\n"
"}\n"
"QLineEdit:disabled {\n"
"\n"
" border:2px solid#0f2027;\n"
" border-radius:4px;\n"
" background:#0f2027;\n"
"}")
        self.search_box.setClearButtonEnabled(True)
        self.search_box.setObjectName("search_box")
        self.btn_search = QtWidgets.QPushButton(self.add_remove_frame_2)
        self.btn_search.setGeometry(QtCore.QRect(570, 50, 69, 25))
        self.btn_search.setMinimumSize(QtCore.QSize(69, 25))
        self.btn_search.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_search.setFont(font)
        self.btn_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_search.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color:#0f2027;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.btn_search.setObjectName("btn_search")
        self.search_feedback = QtWidgets.QLabel(self.add_remove_frame_2)
        self.search_feedback.setGeometry(QtCore.QRect(200, 90, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search_feedback.setFont(font)
        self.search_feedback.setStyleSheet("color: rgb(0, 85, 0);")
        self.search_feedback.setObjectName("search_feedback")
        self.gridLayout_8.addWidget(self.add_remove_frame_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.search_registration)
        self.remove_watchlist = QtWidgets.QWidget()
        self.remove_watchlist.setObjectName("remove_watchlist")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.remove_watchlist)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame_3 = QtWidgets.QFrame(self.remove_watchlist)
        self.frame_3.setMinimumSize(QtCore.QSize(702, 464))
        self.frame_3.setMaximumSize(QtCore.QSize(702, 464))
        self.frame_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame_3.setStyleSheet("background:transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(150, 30, 431, 41))
        self.label_12.setObjectName("label_12")
        self.search_box_2 = QtWidgets.QLineEdit(self.frame_3)
        self.search_box_2.setEnabled(True)
        self.search_box_2.setGeometry(QtCore.QRect(90, 130, 551, 41))
        self.search_box_2.setMinimumSize(QtCore.QSize(400, 25))
        self.search_box_2.setMaximumSize(QtCore.QSize(500000, 250000))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.search_box_2.setFont(font)
        self.search_box_2.setStyleSheet("QLineEdit {\n"
" color:black;\n"
" border:1px solid #0f2027;\n"
" border-radius:4px;\n"
" background:#ffffff;\n"
"}\n"
"QLineEdit:hover {\n"
"\n"
" border:2px solid  #33cc33;\n"
" border-radius:4px;\n"
" background: #ffffff;\n"
"}\n"
"QLineEdit:disabled {\n"
"\n"
" border:2px solid#0f2027;\n"
" border-radius:4px;\n"
" background:#0f2027;\n"
"}")
        self.search_box_2.setClearButtonEnabled(True)
        self.search_box_2.setObjectName("search_box_2")
        self.btn_search_3 = QtWidgets.QPushButton(self.frame_3)
        self.btn_search_3.setGeometry(QtCore.QRect(278, 224, 171, 41))
        self.btn_search_3.setMinimumSize(QtCore.QSize(69, 25))
        self.btn_search_3.setMaximumSize(QtCore.QSize(690, 205))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_search_3.setFont(font)
        self.btn_search_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_search_3.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color:#0f2027;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: red;\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.btn_search_3.setObjectName("btn_search_3")
        self.gridLayout_11.addWidget(self.frame_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.remove_watchlist)
        self.page_android = QtWidgets.QWidget()
        self.page_android.setStyleSheet("background:#FFFFF0\n"
";")
        self.page_android.setObjectName("page_android")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_android)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_android_menu = QtWidgets.QFrame(self.page_android)
        self.frame_android_menu.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_android_menu.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_android_menu.setStyleSheet("background:rgb(51,51,51);")
        self.frame_android_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android_menu.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android_menu.setObjectName("frame_android_menu")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_android_menu)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.lab_user = QtWidgets.QLabel(self.frame_android_menu)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(24)
        self.lab_user.setFont(font)
        self.lab_user.setStyleSheet("color:rgb(255,255,255);")
        self.lab_user.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_user.setObjectName("lab_user")
        self.horizontalLayout_20.addWidget(self.lab_user)
        self.frame_android_contact = QtWidgets.QFrame(self.frame_android_menu)
        self.frame_android_contact.setMinimumSize(QtCore.QSize(80, 30))
        self.frame_android_contact.setMaximumSize(QtCore.QSize(80, 30))
        self.frame_android_contact.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android_contact.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android_contact.setObjectName("frame_android_contact")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_android_contact)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.bn_android_contact = QtWidgets.QPushButton(self.frame_android_contact)
        self.bn_android_contact.setMinimumSize(QtCore.QSize(80, 30))
        self.bn_android_contact.setMaximumSize(QtCore.QSize(80, 30))
        self.bn_android_contact.setStyleSheet("QPushButton {\n"
"    image: url(:/icons/icons/1x/bookAsset 57.png);\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_android_contact.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../../Users/kiongoss/.designer/FinalYearProject/src/icons/1x/bookAsset 57.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_android_contact.setIcon(icon8)
        self.bn_android_contact.setIconSize(QtCore.QSize(13, 16))
        self.bn_android_contact.setFlat(True)
        self.bn_android_contact.setObjectName("bn_android_contact")
        self.horizontalLayout_21.addWidget(self.bn_android_contact)
        self.horizontalLayout_20.addWidget(self.frame_android_contact)
        self.frame_android_game = QtWidgets.QFrame(self.frame_android_menu)
        self.frame_android_game.setMinimumSize(QtCore.QSize(80, 30))
        self.frame_android_game.setMaximumSize(QtCore.QSize(80, 30))
        self.frame_android_game.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android_game.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android_game.setObjectName("frame_android_game")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_android_game)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.bn_android_game = QtWidgets.QPushButton(self.frame_android_game)
        self.bn_android_game.setMinimumSize(QtCore.QSize(80, 30))
        self.bn_android_game.setMaximumSize(QtCore.QSize(80, 30))
        self.bn_android_game.setStyleSheet("QPushButton {\n"
"    image: url(:/icons/icons/1x/gameAsset 61.png);\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_android_game.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../../Users/kiongoss/.designer/FinalYearProject/src/icons/1x/gameAsset 61.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_android_game.setIcon(icon9)
        self.bn_android_game.setIconSize(QtCore.QSize(20, 13))
        self.bn_android_game.setFlat(True)
        self.bn_android_game.setObjectName("bn_android_game")
        self.horizontalLayout_22.addWidget(self.bn_android_game)
        self.horizontalLayout_20.addWidget(self.frame_android_game)
        self.frame_android_clean = QtWidgets.QFrame(self.frame_android_menu)
        self.frame_android_clean.setMinimumSize(QtCore.QSize(80, 30))
        self.frame_android_clean.setMaximumSize(QtCore.QSize(80, 30))
        self.frame_android_clean.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android_clean.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android_clean.setObjectName("frame_android_clean")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_android_clean)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.bn_android_clean = QtWidgets.QPushButton(self.frame_android_clean)
        self.bn_android_clean.setMinimumSize(QtCore.QSize(80, 30))
        self.bn_android_clean.setMaximumSize(QtCore.QSize(80, 30))
        self.bn_android_clean.setStyleSheet("QPushButton {\n"
"    image: url(:/icons/icons/1x/cleanAsset 59.png);\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_android_clean.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../../Users/kiongoss/.designer/FinalYearProject/src/icons/1x/cleanAsset 59.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_android_clean.setIcon(icon10)
        self.bn_android_clean.setFlat(True)
        self.bn_android_clean.setObjectName("bn_android_clean")
        self.horizontalLayout_23.addWidget(self.bn_android_clean)
        self.horizontalLayout_20.addWidget(self.frame_android_clean)
        self.frame_android_world = QtWidgets.QFrame(self.frame_android_menu)
        self.frame_android_world.setMinimumSize(QtCore.QSize(80, 30))
        self.frame_android_world.setMaximumSize(QtCore.QSize(80, 30))
        self.frame_android_world.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android_world.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android_world.setObjectName("frame_android_world")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_android_world)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.bn_android_world = QtWidgets.QPushButton(self.frame_android_world)
        self.bn_android_world.setMinimumSize(QtCore.QSize(80, 30))
        self.bn_android_world.setMaximumSize(QtCore.QSize(80, 30))
        self.bn_android_world.setStyleSheet("QPushButton {\n"
"    image: url(:/icons/icons/1x/worldAsset 60.png);\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_android_world.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../../Users/kiongoss/.designer/FinalYearProject/src/icons/1x/worldAsset 60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_android_world.setIcon(icon11)
        self.bn_android_world.setFlat(True)
        self.bn_android_world.setObjectName("bn_android_world")
        self.horizontalLayout_24.addWidget(self.bn_android_world)
        self.horizontalLayout_20.addWidget(self.frame_android_world)
        spacerItem = QtWidgets.QSpacerItem(397, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.verticalLayout_9.addWidget(self.frame_android_menu)
        self.stackedWidget_android = QtWidgets.QStackedWidget(self.page_android)
        self.stackedWidget_android.setStyleSheet("background:rgb(91,90,90);")
        self.stackedWidget_android.setObjectName("stackedWidget_android")
        self.new_user = QtWidgets.QWidget()
        self.new_user.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(15, 32, 39, 255), stop:1 rgba(255, 255, 240, 255));")
        self.new_user.setObjectName("new_user")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.new_user)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.new_user)
        self.frame_6.setMinimumSize(QtCore.QSize(711, 361))
        self.frame_6.setMaximumSize(QtCore.QSize(711, 361))
        self.frame_6.setStyleSheet("QFrame{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(15, 32, 39, 255), stop:1 rgba(255, 255, 240, 255));\n"
"border-radius:10px;\n"
"box-shadow: 0 3px 10px rgb(0 0 0 / 0.2);\n"
"}\n"
"QLineEdit {\n"
" color:black;\n"
" border:1px solid #0f2027;\n"
" border-radius:4px;\n"
" background:#f2f2f2;\n"
"}\n"
"QLineEdit:hover {\n"
"\n"
" border:2px solid  #33cc33;\n"
" border-radius:4px;\n"
" background: #ffffff;\n"
"}\n"
"QLabel{\n"
"background-color:transparent;\n"
"color:white;\n"
"}\n"
"QLabel:hover{\n"
" color:#33cc33;\n"
"}\n"
"\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.lab_person_icon = QtWidgets.QLabel(self.frame_6)
        self.lab_person_icon.setGeometry(QtCore.QRect(20, 170, 200, 160))
        self.lab_person_icon.setMinimumSize(QtCore.QSize(200, 160))
        self.lab_person_icon.setMaximumSize(QtCore.QSize(200, 160))
        self.lab_person_icon.setStyleSheet("image: url(:/icons/icons/1x/peopleAsset 62.png);")
        self.lab_person_icon.setText("")
        self.lab_person_icon.setPixmap(QtGui.QPixmap("../../../Users/kiongoss/.designer/FinalYearProject/src/icons/1x/peopleAsset 62.png"))
        self.lab_person_icon.setObjectName("lab_person_icon")
        self.bn_android_contact_save = QtWidgets.QPushButton(self.frame_6)
        self.bn_android_contact_save.setEnabled(True)
        self.bn_android_contact_save.setGeometry(QtCore.QRect(580, 260, 69, 25))
        self.bn_android_contact_save.setMinimumSize(QtCore.QSize(69, 25))
        self.bn_android_contact_save.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bn_android_contact_save.setFont(font)
        self.bn_android_contact_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bn_android_contact_save.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"")
        self.bn_android_contact_save.setObjectName("bn_android_contact_save")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(180, 100, 121, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(180, 190, 113, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.lab_android_contact = QtWidgets.QLabel(self.frame_6)
        self.lab_android_contact.setGeometry(QtCore.QRect(50, 10, 171, 31))
        self.lab_android_contact.setMinimumSize(QtCore.QSize(0, 0))
        self.lab_android_contact.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.lab_android_contact.setFont(font)
        self.lab_android_contact.setStyleSheet("color:rgb(255,255,255);")
        self.lab_android_contact.setObjectName("lab_android_contact")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(180, 160, 131, 25))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setGeometry(QtCore.QRect(180, 70, 71, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setGeometry(QtCore.QRect(180, 220, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setGeometry(QtCore.QRect(180, 130, 111, 25))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setGeometry(QtCore.QRect(310, 70, 391, 25))
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 25))
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 100, 391, 25))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(300, 25))
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_3.setGeometry(QtCore.QRect(310, 130, 391, 25))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(300, 25))
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_4.setGeometry(QtCore.QRect(310, 160, 391, 25))
        self.lineEdit_4.setMinimumSize(QtCore.QSize(300, 25))
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_5.setGeometry(QtCore.QRect(310, 190, 391, 25))
        self.lineEdit_5.setMinimumSize(QtCore.QSize(300, 25))
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_6.setGeometry(QtCore.QRect(310, 220, 391, 25))
        self.lineEdit_6.setMinimumSize(QtCore.QSize(300, 25))
        self.lineEdit_6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_6.setClearButtonEnabled(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_4.addWidget(self.frame_6, 0, 0, 1, 1)
        self.stackedWidget_android.addWidget(self.new_user)
        self.users_list = QtWidgets.QWidget()
        self.users_list.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(15, 32, 39, 255), stop:1 rgba(255, 255, 240, 255));")
        self.users_list.setObjectName("users_list")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.users_list)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lab_android_contact_3 = QtWidgets.QLabel(self.users_list)
        self.lab_android_contact_3.setMinimumSize(QtCore.QSize(0, 0))
        self.lab_android_contact_3.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lab_android_contact_3.setFont(font)
        self.lab_android_contact_3.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 240);")
        self.lab_android_contact_3.setObjectName("lab_android_contact_3")
        self.gridLayout_10.addWidget(self.lab_android_contact_3, 0, 0, 1, 1)
        self.system_users_table = QtWidgets.QTableWidget(self.users_list)
        self.system_users_table.setStyleSheet("")
        self.system_users_table.setObjectName("system_users_table")
        self.system_users_table.setColumnCount(0)
        self.system_users_table.setRowCount(0)
        self.gridLayout_10.addWidget(self.system_users_table, 1, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(239, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem1, 2, 1, 1, 1)
        self.bn_android_contact_edit_3 = QtWidgets.QPushButton(self.users_list)
        self.bn_android_contact_edit_3.setMinimumSize(QtCore.QSize(69, 25))
        self.bn_android_contact_edit_3.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bn_android_contact_edit_3.setFont(font)
        self.bn_android_contact_edit_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bn_android_contact_edit_3.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.bn_android_contact_edit_3.setObjectName("bn_android_contact_edit_3")
        self.gridLayout_10.addWidget(self.bn_android_contact_edit_3, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem2, 2, 3, 1, 1)
        self.stackedWidget_android.addWidget(self.users_list)
        self.manage_users = QtWidgets.QWidget()
        self.manage_users.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(15, 32, 39, 255), stop:1 rgba(255, 255, 240, 255));")
        self.manage_users.setObjectName("manage_users")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.manage_users)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_7 = QtWidgets.QFrame(self.manage_users)
        self.frame_7.setMinimumSize(QtCore.QSize(711, 361))
        self.frame_7.setMaximumSize(QtCore.QSize(711, 361))
        self.frame_7.setStyleSheet("QFrame{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(15, 32, 39, 255), stop:1 rgba(255, 255, 240, 255));\n"
"border-radius:10px;\n"
"box-shadow: 0 3px 10px rgb(0 0 0 / 0.2);\n"
"}\n"
"QLineEdit {\n"
" color:black;\n"
" border:1px solid #0f2027;\n"
" border-radius:4px;\n"
" background:#f2f2f2;\n"
"}\n"
"QLineEdit:hover {\n"
"\n"
" border:2px solid  #33cc33;\n"
" border-radius:4px;\n"
" background: #ffffff;\n"
"}\n"
"QLabel{\n"
"background-color:transparent;\n"
"color:white;\n"
"font: 75 12pt \"Arial\";\n"
"}\n"
"QLabel:hover{\n"
" color:#33cc33;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    background#0f2027;\n"
"    color:white;\n"
"} \n"
"QRadioButton::indicator {\n"
"    width:10px;\n"
"    height:10px;\n"
"    border-radius: 7px; }\n"
"QRadioButton::indicator:checked {\n"
"    background-color:#33cc33;\n"
"    border: 2px solid rgb(51,51,51);\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:rgb(91,90,90);\n"
"    border:2px solid rgb(51,51,51);\n"
"}\n"
"\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.bn_android_contact_edit_2 = QtWidgets.QPushButton(self.frame_7)
        self.bn_android_contact_edit_2.setGeometry(QtCore.QRect(310, 330, 69, 25))
        self.bn_android_contact_edit_2.setMinimumSize(QtCore.QSize(69, 25))
        self.bn_android_contact_edit_2.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bn_android_contact_edit_2.setFont(font)
        self.bn_android_contact_edit_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bn_android_contact_edit_2.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.bn_android_contact_edit_2.setObjectName("bn_android_contact_edit_2")
        self.bn_android_contact_delete_2 = QtWidgets.QPushButton(self.frame_7)
        self.bn_android_contact_delete_2.setGeometry(QtCore.QRect(400, 330, 69, 25))
        self.bn_android_contact_delete_2.setMinimumSize(QtCore.QSize(69, 25))
        self.bn_android_contact_delete_2.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bn_android_contact_delete_2.setFont(font)
        self.bn_android_contact_delete_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bn_android_contact_delete_2.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(112,0,0);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.bn_android_contact_delete_2.setObjectName("bn_android_contact_delete_2")
        self.bn_android_contact_save_2 = QtWidgets.QPushButton(self.frame_7)
        self.bn_android_contact_save_2.setEnabled(False)
        self.bn_android_contact_save_2.setGeometry(QtCore.QRect(490, 330, 69, 25))
        self.bn_android_contact_save_2.setMinimumSize(QtCore.QSize(69, 25))
        self.bn_android_contact_save_2.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bn_android_contact_save_2.setFont(font)
        self.bn_android_contact_save_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bn_android_contact_save_2.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.bn_android_contact_save_2.setObjectName("bn_android_contact_save_2")
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setGeometry(QtCore.QRect(90, 190, 121, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setGeometry(QtCore.QRect(90, 250, 113, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.lab_android_contact_2 = QtWidgets.QLabel(self.frame_7)
        self.lab_android_contact_2.setGeometry(QtCore.QRect(50, 10, 171, 31))
        self.lab_android_contact_2.setMinimumSize(QtCore.QSize(0, 0))
        self.lab_android_contact_2.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lab_android_contact_2.setFont(font)
        self.lab_android_contact_2.setStyleSheet("color:rgb(255,255,255);")
        self.lab_android_contact_2.setObjectName("lab_android_contact_2")
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        self.label_13.setGeometry(QtCore.QRect(90, 160, 71, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_7)
        self.label_14.setGeometry(QtCore.QRect(90, 280, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_7)
        self.label_15.setGeometry(QtCore.QRect(90, 220, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("")
        self.label_15.setObjectName("label_15")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_7.setGeometry(QtCore.QRect(220, 160, 391, 25))
        self.lineEdit_7.setMinimumSize(QtCore.QSize(300, 25))
        self.lineEdit_7.setStyleSheet("QLineEdit#lineEdit_7:hover{\n"
"border: 1px solid #0f2027;\n"
"}")
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setClearButtonEnabled(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_8.setGeometry(QtCore.QRect(220, 190, 391, 25))
        self.lineEdit_8.setMinimumSize(QtCore.QSize(300, 25))
        self.lineEdit_8.setStyleSheet("QLineEdit#lineEdit_8:hover{\n"
"border: 1px solid #0f2027;\n"
"}")
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setClearButtonEnabled(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_9.setGeometry(QtCore.QRect(220, 220, 391, 25))
        self.lineEdit_9.setMinimumSize(QtCore.QSize(300, 25))
        self.lineEdit_9.setClearButtonEnabled(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_11.setGeometry(QtCore.QRect(220, 250, 391, 25))
        self.lineEdit_11.setMinimumSize(QtCore.QSize(300, 25))
        self.lineEdit_11.setClearButtonEnabled(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_12.setGeometry(QtCore.QRect(220, 280, 391, 25))
        self.lineEdit_12.setMinimumSize(QtCore.QSize(300, 25))
        self.lineEdit_12.setClearButtonEnabled(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_13.setGeometry(QtCore.QRect(90, 60, 441, 41))
        self.lineEdit_13.setMinimumSize(QtCore.QSize(300, 25))
        self.lineEdit_13.setClearButtonEnabled(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.btn_search_2 = QtWidgets.QPushButton(self.frame_7)
        self.btn_search_2.setGeometry(QtCore.QRect(280, 110, 101, 21))
        self.btn_search_2.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_search_2.setMaximumSize(QtCore.QSize(333443, 349839))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_search_2.setFont(font)
        self.btn_search_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_search_2.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color:#0f2027;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.btn_search_2.setObjectName("btn_search_2")
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_5.setGeometry(QtCore.QRect(90, 110, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setStyleSheet("background:transparent;\n"
"color:black;\n"
"")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_6.setGeometry(QtCore.QRect(210, 110, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setStyleSheet("background:transparent;\n"
"color:black;\n"
"")
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout_9.addWidget(self.frame_7, 0, 0, 1, 1)
        self.stackedWidget_android.addWidget(self.manage_users)
        self.verticalLayout_9.addWidget(self.stackedWidget_android)
        self.stackedWidget.addWidget(self.page_android)
        self.page_logs = QtWidgets.QWidget()
        self.page_logs.setObjectName("page_logs")
        self.gridLayout = QtWidgets.QGridLayout(self.page_logs)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_logs)
        self.scrollArea_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 246, 255), stop:0.55 rgba(255, 255, 225, 255), stop:1 rgba(34, 72, 88, 255));\n"
"")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 700, 462))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_logs)
        self.horizontalLayout_14.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_low = QtWidgets.QFrame(self.frame_bottom_east)
        self.frame_low.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_low.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_low.setStyleSheet("")
        self.frame_low.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_low.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_low.setObjectName("frame_low")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_low)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_tab = QtWidgets.QFrame(self.frame_low)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame_tab.setFont(font)
        self.frame_tab.setStyleSheet("background:#FFFFF0;")
        self.frame_tab.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tab.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_tab.setObjectName("frame_tab")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_tab)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lab_tab = QtWidgets.QLabel(self.frame_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        self.lab_tab.setFont(font)
        self.lab_tab.setStyleSheet("color:rgb(255,255,255);")
        self.lab_tab.setObjectName("lab_tab")
        self.horizontalLayout_12.addWidget(self.lab_tab)
        self.horizontalLayout_11.addWidget(self.frame_tab)
        self.frame_drag = QtWidgets.QFrame(self.frame_low)
        self.frame_drag.setMinimumSize(QtCore.QSize(20, 20))
        self.frame_drag.setMaximumSize(QtCore.QSize(20, 20))
        self.frame_drag.setStyleSheet("background:#FFFFF0;")
        self.frame_drag.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_drag.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_drag.setObjectName("frame_drag")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_drag)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_11.addWidget(self.frame_drag)
        self.verticalLayout_2.addWidget(self.frame_low)
        self.horizontalLayout_2.addWidget(self.frame_bottom_east)
        self.gridLayout_3.addWidget(self.frame_bottom, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_android.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab_appname.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bn_min.setToolTip(_translate("MainWindow", "Minimize"))
        self.bn_max.setToolTip(_translate("MainWindow", "Maximize"))
        self.bn_close.setToolTip(_translate("MainWindow", "Close"))
        self.bn_home.setToolTip(_translate("MainWindow", "Home"))
        self.bn_bug.setToolTip(_translate("MainWindow", "Bug"))
        self.bn_cloud.setToolTip(_translate("MainWindow", "Cloud"))
        self.bn_android.setToolTip(_translate("MainWindow", "Android"))
        self.add_remove_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">ADD TO WATCHLIST</span></p></body></html>"))
        self.car_deatils_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">CAR DETAILS</span></p></body></html>"))
        self.reg_plate_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Registration Plate :</span></p></body></html>"))
        self.owner_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Owner :</span></p></body></html>"))
        self.vehicle_make_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Vehicle Make :</span></p></body></html>"))
        self.year_of_man_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Year of Manufacture :</span></p></body></html>"))
        self.engine_capacity_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Engine Capacity :</span></p></body></html>"))
        self.body_type_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Vehicle Body Type :</span></p></body></html>"))
        self.color_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Color :</span></p></body></html>"))
        self.logbook_number_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Registered Logbook Number :</span></p></body></html>"))
        self.engine_number_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Registration Engine Number :</span></p></body></html>"))
        self.chassis_number_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Registration Chassis Number :</span></p></body></html>"))
        self.btn_save_to_wishlist.setText(_translate("MainWindow", "SAVE CHANGES"))
        self.add_remove_label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">SEARCH REGISTRATION DETAILS</span></p></body></html>"))
        self.car_deatils_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">CAR DETAILS</span></p></body></html>"))
        self.reg_plate_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Registration Plate :</span></p></body></html>"))
        self.owner_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Owner :</span></p></body></html>"))
        self.vehicle_make_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Vehicle Make :</span></p></body></html>"))
        self.year_of_man_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Year of Manufacture :</span></p></body></html>"))
        self.engine_capacity_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Engine Capacity :</span></p></body></html>"))
        self.body_type_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Vehicle Body Type :</span></p></body></html>"))
        self.color_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Color :</span></p></body></html>"))
        self.logbook_number_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Registered Logbook Number :</span></p></body></html>"))
        self.engine_number_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Registration Engine Number :</span></p></body></html>"))
        self.chassis_number_label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Registration Chassis Number :</span></p></body></html>"))
        self.btn_search.setText(_translate("MainWindow", "search"))
        self.search_feedback.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">REMOVE VEHICLE FROM WATCHLIST</span></p></body></html>"))
        self.search_box_2.setPlaceholderText(_translate("MainWindow", "         Enter vehicle plate number to be removed from watchlist"))
        self.btn_search_3.setText(_translate("MainWindow", "Remove"))
        self.lab_user.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">User8455</span></p></body></html>"))
        self.bn_android_contact.setToolTip(_translate("MainWindow", "Contact"))
        self.bn_android_game.setToolTip(_translate("MainWindow", "GamePad"))
        self.bn_android_clean.setToolTip(_translate("MainWindow", "Clean"))
        self.bn_android_world.setToolTip(_translate("MainWindow", "World"))
        self.bn_android_contact_save.setText(_translate("MainWindow", "Save"))
        self.label_5.setText(_translate("MainWindow", "Staff Number :"))
        self.label_7.setText(_translate("MainWindow", "Email:"))
        self.lab_android_contact.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Register new user</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">confirm password:</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Name: "))
        self.label_8.setText(_translate("MainWindow", "Phone:"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Password :</span></p></body></html>"))
        self.lab_android_contact_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">System users </span></p></body></html>"))
        self.bn_android_contact_edit_3.setText(_translate("MainWindow", "Print"))
        self.bn_android_contact_edit_2.setText(_translate("MainWindow", "Update"))
        self.bn_android_contact_delete_2.setText(_translate("MainWindow", "Delete"))
        self.bn_android_contact_save_2.setText(_translate("MainWindow", "Save"))
        self.label_9.setText(_translate("MainWindow", "Staff Number :"))
        self.label_11.setText(_translate("MainWindow", "Email:"))
        self.lab_android_contact_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Manage users </span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "Name: "))
        self.label_14.setText(_translate("MainWindow", "Phone:"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>Role :</p></body></html>"))
        self.lineEdit_13.setPlaceholderText(_translate("MainWindow", "         Enter staff number /email"))
        self.btn_search_2.setText(_translate("MainWindow", "Search user"))
        self.radioButton_5.setText(_translate("MainWindow", "Staff number"))
        self.radioButton_6.setText(_translate("MainWindow", "Email"))
        self.lab_tab.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.frame_drag.setToolTip(_translate("MainWindow", "Drag"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
